// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://takwqjarxdfskjgpsjde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRha3dxamFyeGRmc2tqZ3BzamRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxMjA2MTgsImV4cCI6MjA2NzY5NjYxOH0.j0egeNsS5zcxPlWI0mx_gYKRyQ9gXRSoTxmO2XmJg7Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});